### ISSUE TITLE
Trained DPR on HotpotQA

### ISSUE THREAD

**Issue by GSidiropoulos** [facebookresearch/multihop_dense_retrieval#10]
Dear authors,

Thank you very much for sharing your work! I was wondering if you have available and can share with us, the trained on HotpotQA DPR model (the one you refer to as "single-hop" on Table 3).

Best wishes

**Comment by xwhan** [comment]
Hi, we have an archived python file on training single hop models: check [this](https://github.com/facebookresearch/multihop_dense_retrieval/blob/master/mdr/retrieval/train_single.py). You could use it for single-hop dataset and should give you very good numbers.
