### ISSUE TITLE
MHopRetreiver

### ISSUE THREAD

**Issue by Cheng-Cheng2** [facebookresearch/multihop_dense_retrieval#16]
In your train_mhop.py script and your training example, your were using a MhopRetriever imported from mdr.retrieval.models.mhop_retriever. However, this class is not present in the script. Could you verify if instead the RobertaRetriever was used to achieve the results in the paper? Thanks.

**Comment by xwhan** [comment]
Yes, we only used RobertaRetriever when reporting the numbers
