### ISSUE TITLE
Why masking the 1st hop?

### ISSUE THREAD

**Issue by yangky11** [facebookresearch/multihop_dense_retrieval#20]
Hi,

Thanks for releasing the code! I have a minor question about this piece of code:
https://github.com/facebookresearch/multihop_dense_retrieval/blob/62eb2427e36a648a927c6e39bb4c748796f7b366/mdr/retrieval/criterions.py#L127-L130
I'm wondering what's the purpose of masking the 1st hop? Does it help the final experimental results? Thanks!

**Comment by xwhan** [comment]
Hi @yangky11,  the reason behind this was to avoid labeling the 2-hop supporting passage as negatives. Sometimes, the hop order might not be obvious and this is especially true for comparison questions. This gave some improvements on some initial experiments.

**Comment by yangky11** [comment]
That makes sense. Thank you!
