### ISSUE TITLE
How to Perform the Reranking Step?

### ISSUE THREAD

**Issue by yangky11** [facebookresearch/multihop_dense_retrieval#21]
Hi,

Thanks for sharing the code! I read from the paper that there is a reranking step before training the reader, but I'm unable to find how is it performed by following the README. Is reranking necessary? How to do it in the current repo? Thank you!

Best regards,

**Comment by yangky11** [comment]
Also, are the provided files (`data/hotpot/train_retrieval_b100_k100_sp.json` and `data/hotpot/dev_retrieval_b50_k50_sp.json`) with or without reranking?

**Comment by xwhan** [comment]
Those files are without reranking. The reranking part is inside the reader model. It might not be necessary to add an additional reranking phrase before the reader model. [https://github.com/facebookresearch/multihop_dense_retrieval/blob/main/mdr/qa/qa_model.py#L43](https://github.com/facebookresearch/multihop_dense_retrieval/blob/main/mdr/qa/qa_model.py#L43)

**Comment by yangky11** [comment]
Thanks!
