### ISSUE TITLE
Four-Hop Training?

### ISSUE THREAD

**Issue by okhat** [facebookresearch/multihop_dense_retrieval#4]
Hi! Thanks for the great paper and for the code release!

I'm curious if it's straightforward to train a three- or four-hop retriever using this code. I can create something like `hotpot_train_with_neg_v0.json` and, instead of one `bridge`, have a list of 2--3 bridges for each example.

I see that I need to modify only `mhop_dataset.py` (which is used from `train_mhop.py`) so it uses the modified bridges. Do you expect this to be a simple modification? It seems that some of the remaining code also assumes at most one bridge?

**Comment by xwhan** [comment]
Hi Omar, it should be easy to modify the code the support more hops. Besides the `mhop_dataset.py`, you will need to modify
* [the model](https://github.com/facebookresearch/multihop_dense_retrieval/blob/master/mdr/retrieval/models/mhop_retriever.py#L28) to encode the query/target in multiple hops
* [loss function and validation metrics](https://github.com/facebookresearch/multihop_dense_retrieval/blob/master/mdr/retrieval/criterions.py#L114)
* validation code snippets in `train_mhop.py`

**Comment by okhat** [comment]
Thank you Wenhan!

It seems a little more involved than I hoped, unfortunately. I will close this issue for now; will reopen if necessary.
